# .github/workflows/main.yml
name: Main Taski workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    # Разворачиваем окружение:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.10
        # Указываем имя тестовой базы, имя и пароль пользователя в открытом виде,
        # ведь эта база будет работать только во время прогона тестов
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        # Эта конструкция описывает проверку готовности сервиса postgres
        # Если её не будет, то тесты могут запуститься раньше, чем сервер PostgreSQL
        # В результате тесты опять решат, что базы нет, — и упадут
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    # Копируем код проекта
    - name: Check out code
      uses: actions/checkout@v4
    # Устанавливаем Python с помощью action
    - name: Set up Python
      uses: actions/setup-python@v5
    # В action setup-python передаём параметр — версию Python
      with:
        python-version: "3.10"
    # Обновляем pip, устанавливаем ruff
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r backend/requirements.txt
        pip install ruff==0.8.0
    # Запускаем ruff
    - name: Lint with ruff and run django tests
      env:
        POSTGRES_USER: django_user
        POSTGRES_PASSWORD: django_password
        POSTGRES_DB: django_db
        # Сервер БД запущен в Docker, но его порт проброшен на хост
        # Поэтому подключаемся к 127.0.0.1:5432
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        python -m ruff check backend/
        cd backend/
        python manage.py test